### ISSUE TITLE
[SOLVED] DokuWiki stops work (HTTP 500) if I use some bootswrapper extension in page

### ISSUE THREAD

**Issue by waldauf** [LotarProject/dokuwiki-plugin-bootswrapper#75]
Hello,

I have installed bootswrapper plugin into my DokuWiki. The plugin is by default enabled. If I place into page some bootswrapper extension the page is returning HTTP 500. I tested it on DW versions 2017-02-19e and 2016-06-26e, but with the same result - HTTP 500.

----
Plugin is **enabled**:
![disabled](https://user-images.githubusercontent.com/24603883/30738291-ec40f3cc-9f89-11e7-85df-2e44792a71f5.png)

----
Plugin is **disabled**:
![enabled](https://user-images.githubusercontent.com/24603883/30738298-ef0b8766-9f89-11e7-87b6-e5ed0b8a6312.png)

----

Can I ask you for help? All extensions from this plugin I would like to use (mainly dropdown menu), but it doesn't work on my DokuWiki. If you need some additional information write me.

**Comment by waldauf** [comment]
I tried to change permissions to 755 and 777 but without success.

**Comment by LotarProject** [comment]
Hi,
to investigate the problem, you can add the last lines of your `error_log` ?

Joseph

**Comment by waldauf** [comment]
Hi,

yes of course. I should it immediately:
```
wiki_1  | 2017-09-22 11:18:44,209 CRIT Supervisor running as root (no user in config file)
wiki_1  | 2017-09-22 11:18:44,217 INFO RPC interface 'supervisor' initialized
wiki_1  | 2017-09-22 11:18:44,217 CRIT Server 'unix_http_server' running without any HTTP authentication checking
wiki_1  | 2017-09-22 11:18:44,217 INFO supervisord started with pid 1
wiki_1  | 2017-09-22 11:18:45,222 INFO spawned: 'nginx' with pid 12
wiki_1  | 2017-09-22 11:18:45,227 INFO spawned: 'php' with pid 13
wiki_1  | 2017-09-22 11:18:46,368 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
wiki_1  | 2017-09-22 11:18:46,368 INFO success: php entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
wiki_1  | 2017/09/22 11:19:32 [error] 14#14: *4 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_string() in /var/www/lib/plugins/bootswrapper/syntax/bootstrap.php:215
wiki_1  | Stack trace:
wiki_1  | #0 /var/www/inc/parser/handler.php(80): syntax_plugin_bootswrapper_bootstrap->handle('<btn type="prim...', 1, 21, Object(Doku_Handler))
wiki_1  | #1 /var/www/inc/parser/lexer.php(526): Doku_Handler->plugin('<btn type="prim...', 1, 21, 'bootswrapper_bu...')
wiki_1  | #2 /var/www/inc/parser/lexer.php(461): Doku_Lexer->_invokeParser('<btn type="prim...', 1, 21)
wiki_1  | #3 /var/www/inc/parser/lexer.php(411): Doku_Lexer->_dispatchTokens('', '<btn type="prim...', 'plugin_bootswra...', 21, 21)
wiki_1  | #4 /var/www/inc/parser/parser.php(120): Doku_Lexer->parse('Primary</btn>\n')
wiki_1  | #5 /var/www/inc/parserutils.php(205): Doku_Parser->parse('\n====== TEST ==...')
wiki_1  | #6 /var/www/inc/parserutils.php(167): p_get_instructions('====== TEST ===...')
wiki_1  | #7 /var/www/inc/parserutils.php(480): p_cached_instructions('/var/www/data/p...', false, 'test:test')
wiki_1  | #8 /var/www/inc/parserutils.php(270): p_rende" while reading response header from upstream, client: 172.21.0.1, server: , request: "GET /doku.php?id=test:test HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm7.sock:", host: "localhost:8090"
```
I found out if I use bootswrapper syntax and try to restart DW it can't run and in log I see:
```
wiki_1  | test:test... E: Error: Call to undefined function simplexml_load_string() in /var/www/lib/plugins/bootswrapper/syntax/bootstrap.php:215
wiki_1  | Stack trace:
wiki_1  | #0 /var/www/inc/parser/handler.php(80): syntax_plugin_bootswrapper_bootstrap->handle('<btn type="prim...', 1, 21, Object(Doku_Handler))
wiki_1  | #1 /var/www/inc/parser/lexer.php(526): Doku_Handler->plugin('<btn type="prim...', 1, 21, 'bootswrapper_bu...')
wiki_1  | #2 /var/www/inc/parser/lexer.php(461): Doku_Lexer->_invokeParser('<btn type="prim...', 1, 21)
wiki_1  | #3 /var/www/inc/parser/lexer.php(411): Doku_Lexer->_dispatchTokens('', '<btn type="prim...', 'plugin_bootswra...', 21, 21)
wiki_1  | #4 /var/www/inc/parser/parser.php(120): Doku_Lexer->parse('Primary</btn>\n')
wiki_1  | #5 /var/www/inc/parserutils.php(205): Doku_Parser->parse('\n====== TEST ==...')
wiki_1  | #6 /var/www/inc/parserutils.php(167): p_get_instructions('====== TEST ===...')
wiki_1  | #7 /var/www/inc/parserutils.php(480): p_cached_instructions('/var/www/data/p...', false, 'test:test')
wiki_1  | #8 /var/www/inc/parserutils.php(270): p_render_metadata('test:test', Array)
wiki_1  | #9 /var/www/inc/indexer.php(1392): p_get_metadata('test:test', 'internal index', 4)
wiki_1  | #10 /var/www/bin/indexer.php(78): idx_addPage('test:test', true, true)
wiki_1  | #11 /var/www/bin/indexer.php(67): IndexerCLI->index('test:test')
wiki_1  | #12 /var/www/bin/indexer.php(53): IndexerCLI->update()
wiki_1  | #13 /var/www/inc/cli.php(85): IndexerCLI->main(Object(DokuCLI_Options))
wiki_1  | #14 /var/www/bin/indexer.php(103): DokuCLI->run()
wiki_1  | #15 {main}
```

**Comment by LotarProject** [comment]
Thanks!

The problem is the missing PHP library (php-xml). If you have a Debian/Ubuntu distro you can install it via apt-get:

```
apt-get install php-xml
```

**Comment by waldauf** [comment]
I thought that also but these packages are defined to install during creating docker container:
```
apk --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ add php7 php7-fpm php7-gd php7-openssl php7-session php7-xml php7-zlib php7-ldap nginx supervisor curl tar
```
I logged into container and try to install php7-xml again:
```
bash-4.3# apk --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ add php7-xml
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
OK: 108 MiB in 63 packages
```

Result is still the same - HTTP 500.

**Comment by LotarProject** [comment]
You can verify module loading ?

```
php -m | grep -i simplexml
```

**Comment by waldauf** [comment]
I checked it and found out missing simplexml modul which is in php7-simplexml package. I installed it and now it is working. Many thx for your immediate help I really appreciate it. :]

I'm not php developer and cannot say... But try consider to write php module dependecies. It could help you with such problem like was mine. ;]

**Comment by LotarProject** [comment]
;)
I have updated the documentation in dokuwiki.org.

Best regards,
Joseph
